version: 0.2

env:
  variables:
    ECR_REPOSITORY_NAME: "sai-kumar/my-images"
    AWS_ACCOUNT_ID: "522814713874" 
    AWS_REGION: "us-east-1"
    DOCKER_IMAGE_TAG: "latest"
    # Git repository variables
    GIT_REPOSITORY_URL: "https://github.com/SaiKumarBalabadra/python-demoapp.git"
    GIT_BRANCH: "main"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      # Set AWS account ID and region
      - export AWS_DEFAULT_REGION=us-east-1
      - export AWS_ACCOUNT_ID=522814713874
      - export ECR_REPO_URI=522814713874.dkr.ecr.us-east-1.amazonaws.com/sai-kumar/my-images
      - export ECR_REPOSITORY_NAME=sai-kumar/my-images
      - export AWS_REGION=us-east-1
      - export DOCKER_IMAGE_TAG=latest

  pre_build:
    commands:
      # Clone the source code
      - git clone $GIT_REPOSITORY_URL source
      - cd source
      
      # Login to AWS ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 522814713874.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      # Build Docker image
      - docker build -t $ECR_REPOSITORY_NAME:$DOCKER_IMAGE_TAG .
      - docker tag $ECR_REPOSITORY_NAME:$DOCKER_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$DOCKER_IMAGE_TAG

  post_build:
    commands:
      # Push Docker image to ECR
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$DOCKER_IMAGE_TAG
      
      # Save build information
      - echo Build completed on `date`
      - echo "Image pushed to $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$DOCKER_IMAGE_TAG"

artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
